name: Build

on:
  push:
    branches-ignore:
      - master
    tags-ignore:
      - v.*
  pull_request:
    branches:
      - "*"

env:
  MINIMUM_PYTHON_VERSION: "3.9"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.9","3.10","3.11","3.12"]

    steps:
      #----------------------------------------------
      #       check-out repo
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v4
      
      #----------------------------------------------
      #  -----  install & configure python & rye  -----
      #----------------------------------------------
      - name: Set up the environment
        uses: ./.github/actions/setup-python-env
        with:
          python-version: ${{ env.MINIMUM_PYTHON_VERSION }}
      - name: Test with pytest
        run: make test
