name: Build & Publish

on:
  push:
    branches:
      - master
    tags:
      - v0.*

env:
  MINIMUM_PYTHON_VERSION: "3.9"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.9","3.10","3.11","3.12"]
    steps:
      #----------------------------------------------
      #       check-out repo
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v4
      
      #----------------------------------------------
      #  -----  install & configure python & rye  -----
      #----------------------------------------------
      - name: Set up the environment
        uses: ./.github/actions/setup-python-env
        with:
          python-version: ${{ env.MINIMUM_PYTHON_VERSION }}
      - name: Test with pytest
        run: make test
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      #----------------------------------------------
      #  -----  install & configure rye  -----
      #----------------------------------------------
      - name: Install rye
        id: setup-rye
        uses: eifinger/setup-rye@5b24b104a68da1e2ea0073aa191a2bab66f55d7c
      
      - name: Set up python ${{ env.MINIMUM_PYTHON_VERSION }}
        run: rye pin ${{ env.MINIMUM_PYTHON_VERSION }}
      #----------------------------------------------
      #  -----  build distribution -----
      #----------------------------------------------
      - name: Build distribution
        run: rye build
      - name: Publish package to PyPI
        if: github.repository == 'spraakbanken/paradigmextract' && startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@release/v1
